services:
  fastapi:
    build: .
    env_file:
      - stack.env
    ports:
      - "8021:8021"
    restart: unless-stopped
    environment:
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      db:
        condition: service_healthy

  cloudflared:
    image: cloudflare/cloudflared:latest
    command: tunnel --no-autoupdate run --url http://fastapi:8021
    env_file:
      - stack.env
    depends_on:
      - fastapi
    restart: unless-stopped

  db:
    image: timescale/timescaledb:latest-pg17
    env_file:
      - stack.env
    ports:
      - "5432:5432"
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
      - db_data_${STACK_VERSION:-v1}:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      retries: 5
      start_period: 5s
    restart: unless-stopped

volumes:
  db_data_${STACK_VERSION:-v1}: